"""
Package landmapy.

Functions:
    cdcplaces.shp_tract_path(data_dir, place = 'chicago-tract')
    cdcplaces.download_census_tract(tract_path, placename = 'Chicago')
    cdcplaces.hvplot_tract_gdf(place_tract_gdf)
    cdcplaces.download_cdc_disease(data_dir)
    cdcplaces.join_tract_cdc(place_tract_gdf, cdc_df)
    cdcplaces.plot_gdf_gv(tract_cdc_gdf)
    check.header_csv(file_path)
    check.get_last_row_csv(file_path)
    check.check_element_in_csv(filename, column_name, target_value)
    check.check_naip_tracts(naip_index_path, naip_scenes_df)
    explore.merge_ndvi_cdc(tract_cdc_gdf, ndvi_index_df)
    explore.plot_chloropleth(gdf)
    explore.plot_ndvi_index(ndvi_cdc_gdf)
    explore.var_trans(ndvi_cdc_gdf)
    explore.hvplot_matrix(model_df)
    explore.train_test(model_df)
    explore.plot_train_test(y_test)
    explore.plot_resid(model_df, reg)
    habitat.robust_code()
    habitat.creata_data_dir(new_dir)
    habitat.gdf_da_bounds(place_gdf, da, buffer)
    habitat.ramp_logic(data, up, down)
    index.plot_index(city_ndvi_da, city)
    index.plot_gdf_da(place_gdf, index_da)
    index.redline_mask(city_redlining_gdf, city_ndvi_da)
    index.redline_index_gdf(redlining_gdf, ndvi_stats)
    index.index_grade_hv(redlining_ndvi_gdf, city)
    index.index_tree(redlining_ndvi_gdf)
    index.plot_index_pred(redlining_ndvi_gdf, tree_classifier, city)
    naip.naip_path(data_dir, place = 'chicago')
    naip.download_naip_scenes(naip_index_path, tract_cdc_gdf)
    naip.ndvi_naip_one(tract_cdc_gdf, tract, tract_date_gdf)
    naip.ndvi_naip_df(naip_index_path, tract_cdc_gdf, naip_scenes_df)
    naip.check_element_in_csv(filename, column_name, target_value)
    polaris.soil_url_dict(place_gdf, soil_var, soil_sum, soil_depth)
    polaris.merge_soil(place_gdf, soil_var, soil_sum, soil_depth, buffer)
    process.process_image(uri, bounds_gdf)
    process.process_cloud_mask(cloud_uri, bounds_gdf, bits_to_mask)
    process.process_metadata(city_files)
    process.process_bands(city_gdf, raster_df)
    redline.redline_gdf(data_dir)
    redline.plot_gdf_state(redlining_gdf)
    srtm.srtm_download(place_gdf, elevation_dir, buffer)
    srtm.srtm_slope(srtm_da, UTM)
    thredds.process_maca(sites, scenarios, climates, years, buffer)
    thredds.maca_year(maca_df, row, year)
Deprecated:
    index.redline_over_index(city_redlining_gdf, city_ndvi_da)
    redline.plot_redline(redlining_gdf)
"""